FROM debian:bullseye

RUN apt-get update && apt-get install -y \
	vsftpd \
	ftp \
	&& rm -rf /var/lib/apt/lists/*

# Create FTP user
RUN useradd -m $FTP_USER && \
	echo "$FTP_USER:$FTP_PWD" | chpasswd

RUN mkdir -p /var/www/html && \
	chmod 775 /var/www/html && \
	chown -R www-data:www-data /var/www/html

RUN mkdir -p /var/run/vsftpd/empty && \
	chmod 755 /var/run/vsftpd/empty

RUN usermod -aG www-data ftpuser


# Copy vsftpd configuration
COPY conf/vsftpd.conf /etc/vsftpd.conf
COPY conf/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 21 21000-21010

ENTRYPOINT ["/entrypoint.sh"]
