FROM debian:bullseye

RUN apt-get update && apt-get install -y \
	vsftpd \
	ftp \
	&& rm -rf /var/lib/apt/lists/*

# Create FTP user
RUN useradd -m ftpuser && \
	echo "ftpuser:ftppassword" | chpasswd

# Create directory that will map to WordPress volume
RUN mkdir -p /var/www/html && \
	chown -R ftpuser:ftpuser /var/www/html

# Copy vsftpd configuration
COPY conf/vsftpd.conf /etc/vsftpd.conf

EXPOSE 21 21000-21010

CMD ["vsftpd", "/etc/vsftpd.conf"]
